# 使用说明 V3.4.0
# 1. 使用docker-compose  宿主机不需要配置host来发现
# 2. 无需修改源码，根目录  docker-compose up 即可
# 3. 静静等待服务启动

version: '2'
services:
  ruoyi-eureka:
    build:
      context: ./
      dockerfile: ./ruoyi-eureka/Dockerfile
    restart: always
    image: java:8
    container_name: ruoyi-eureka
    network_mode: host
    ports:
      - 7001:7001

  ruoyi-config:
    build:
      context: ./
      dockerfile: ./ruoyi-config/Dockerfile
    restart: always
    image: java:8
    container_name: ruoyi-config
    network_mode: host
    depends_on:
      - ruoyi-eureka
    ports:
      - 8888:8888

  ruoyi-gateway:
    build:
      context: ./
      dockerfile: ./ruoyi-gateway/Dockerfile
    restart: always
    image: java:8
    container_name: ruoyi-gateway
    network_mode: host
    depends_on:
      - ruoyi-eureka
      - ruoyi-config
    ports:
      - 9527:9527

  ruoyi-auth:
    build:
      context: ./
      dockerfile: ./ruoyi-service/ruoyi-auth/Dockerfile
    restart: always
    image: java:8
    container_name: ruoyi-auth
    network_mode: host
    depends_on:
      - ruoyi-eureka
      - ruoyi-config
    ports:
      - 8005:8005

  ruoyi-fabric:
    build:
      context: ./
      dockerfile: ./ruoyi-service/ruoyi-fabric/Dockerfile
    restart: always
    image: java:8
    container_name: ruoyi-fabric
    network_mode: host
    depends_on:
      - ruoyi-eureka
      - ruoyi-config
    ports:
      - 9999:9999
    volumes:
      - /home/aca:/home/aca

  ruoyi-mb-system:
    build:
      context: ./
      dockerfile: ./ruoyi-service/ruoyi-mb-system/Dockerfile
    restart: always
    image: java:8
    container_name: ruoyi-mb-system
    network_mode: host
    depends_on:
      - ruoyi-eureka
      - ruoyi-config
    ports:
      - 8111:8111

  ruoyi-system:
    build:
      context: ./
      dockerfile: ./ruoyi-service/ruoyi-system/Dockerfile
    restart: always
    image: java:8
    container_name: ruoyi-system
    network_mode: host
    depends_on:
      - ruoyi-eureka
      - ruoyi-config
    ports:
      - 8001:8001