server:
  port: 8011
# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn
spring:
  application:
    name: ruoyi-acad
  cloud:
    config:
      fail-fast: true
      name: ${spring.application.name}
      profile: ${spring.profiles.active}
      discovery:
        enabled: true
        service-id: ruoyi-config
  profiles:
    active: prod
  devtools:
    restart:
      enabled: true
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      maxFileSize: 5MB  #单位必须大写MB或不写(即为B)
      maxRequestSize: 10MB

feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址
# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
#mybatis plus 设置
mybatis-plus:
  type-aliases-package: com.ruoyi.javamail.entity
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
    call-setters-on-nulls: true
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false
fdfs:
  so-timeout: 1501 #上传的超时时间
  connect-timeout: 601 #连接超时时间
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.8.20:22122
  http:
    anti_steal_token: true
    secret_key: MingbyteAcademician
  web-server-url: www.mingbyte.com:1234