server: 
  port: 9527
 
spring: 
  application:
    name: ruoyi-gateway
  devtools:
    restart:
      enabled: true
  profiles:
    active: dev
  cloud:
    config:
      fail-fast: true
      name: ${spring.application.name}
      profile: ${spring.profiles.active}
      discovery:
        enabled: true
        service-id: ruoyi-config
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # 认证中心
        - id: ruoyi-auth
          uri: lb://ruoyi-auth
          predicates:
            - Path=/auth/**
          filters:
            # 验证码处理
            - CacheRequest
            - ImgCodeFilter
            - StripPrefix=1
        # 代码生成
        - id: ruoyi-gen
          uri: lb://ruoyi-gen
          predicates:
            - Path=/gen/**
          filters:
            - StripPrefix=1
        # fdfs
        - id: ruoyi-fdfs
          uri: lb://ruoyi-fdfs
          predicates:
            - Path=/fdfs/**
          filters:
            - StripPrefix=1
        # javamail
        - id: ruoyi-javamail
          uri: lb://ruoyi-javamail
          predicates:
            - Path=/javamail/**
          filters:
            - StripPrefix=1
        # acad
        - id: ruoyi-acad
          uri: lb://ruoyi-acad
          predicates:
            - Path=/acad/**
          filters:
            - StripPrefix=1
        # fabric
        - id: ruoyi-fabric
          uri: lb://ruoyi-fabric
          predicates:
            - Path=/fabric/**
          filters:
            - StripPrefix=1
        # act
        - id: ruoyi-activiti
          uri: lb://ruoyi-activiti
          predicates:
            - Path=/act/**
          filters:
            - StripPrefix=1
        #system 模块
        - id: ruoyi-system
          uri: lb://ruoyi-system
          predicates:
            - Path=/system/**
          filters:
            # 限流配置
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
              # 降级配置
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: 'forward:/fallback'
        #mingbyte system 模块
        - id: ruoyi-mb-system
          uri: lb://ruoyi-mb-system
          predicates:
            - Path=/mb-system/**
          filters:
            # 限流配置
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
              # 降级配置
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: 'forward:/fallback'

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
       defaultZone: http://127.0.0.1:7001/eureka
       #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      
  instance:
    instance-id:  ${spring.application.name}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址      

ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 10000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 2000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000 #断路器超时时间，默认1000ms

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'