spring:
  redis:
    cluster:
      nodes:
        - 192.168.8.187:9001
        - 192.168.8.187:9002
        - 192.168.8.187:9003
        - 192.168.8.189:9004
        - 192.168.8.189:9005
        - 192.168.8.189:9006
      connectionTimeout: 6000
      soTimeout: 6000
      maxAttempts: 5
      password: Mingbyte@123 #写正确的密码
fdfs:
  so-timeout: 1501 #上传的超时时间
  connect-timeout: 601 #连接超时时间
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.8.20:22122
  http:
    anti_steal_token: true
    secret_key: MingbyteAcademician
  web-server-url: www.mingbyte.com:1234